# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumbe:
            quality: 75
            filters:
                thumbnail: { size: [700, 530], mode: outbound }
        medium:
            quality: 75
            filters:
                thumbnail: { size: [1000, 1000], mode: outbound }                

                
    
